<?php
if(!defined('THINK_PATH')) exit();
return $array = array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => '47.92.71.173',
  'DB_NAME' => 'weixinsaoyisao',
  'DB_USER' => 'root',
  'DB_PWD' => '583185670DXdx||',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'wxq_',
  'DB_BACKUP' => '../Data/backup',
  'RBAC_ROLE_TABLE' => 'wxq_role',
  'RBAC_USER_TABLE' => 'wxq_user',
  'RBAC_ACCESS_TABLE' => 'wxq_access',
  'RBAC_NODE_TABLE' => 'wxq_node',
  'URL_CASE_INSENSITIVE' => true,
  'URL_MODEL' => 2,
  'DEFAULT_THEME' => 'mobile',
  'WX_TOKEN' => 'yf519ee20672526684232448',
  'SITE_NAME' => '微分享',
  'SITE_TITLE' => '微分享',
  'SITE_KEYWORDS' => '微信群|微信群分享|微信群导航|微信群大全|微信红包|微信红包群|红包群|微信个人号|微信公众号|微信群导航|微信群二维码|微信群推荐|微信群聊|微信加群|微商货源|微信营销|微信推广|微信群人数上限|微信群怎么建|微信群怎么找',
  'SITE_DESCRIPTION' => '最具人气的微信群导航,为大家提供各地区各兴趣的微信群二维码图片,大家可以根据需要找到自己感兴趣的微信群,我们的目标是做最好的微信群聊推荐网站。查看群二维码，提交群信息，让大家快速找到自己喜爱的微信群。',
  'RMB_CHANGE_INTERGRAL' => 20,
  'ISCOMMENT' => 1,
  'COMMENTTYPE' => 1,
  'ISADDACCOUNT' => 1,
  'XFINTERGRAL' => 10,
  'ISAUTOVERIFY' => 0,
  'YUFUMARK' => '',
  'ISTASK' => 0,
  'TASKURL' => '',
  'URL_PATHINFO_DEPR' => '-',
);
?>